name: CI-CD

on:
  push:
    branches: [ master ]

# Set env variables
env:
  HEROKU_EMAIL: ${{ secrets.EMAIL }}
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  APP_NAME: ${{ 'waterfall-skdfnodfnsdi' }}
  DOCKER_SECRET: ${{ secrets.DOCKER_SECRET }}
  DOCKER_ID: ${{ secrets.DOCKER_ID }}
    
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      #Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout-repo
        uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@master
        with:
          node-version: 17.x

      - name: install dependencies      
        run: |
          npm install
          npm ci

  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: checkout-repo
        uses: actions/checkout@v2

      - run: npm run build

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: checkout-repo
        uses: actions/checkout@v2

      - run: npm run test
  
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      # Clone the repository
      - name: checkout-repo
        uses: actions/checkout@v2

      - name: push heroku master
        uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: $HEROKU_API_KEY
          heroku_app_name: $APP_NAME
          heroku_email: $HEROKU_EMAIL
          usedocker: true